org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.daemon=true
android.enableDxe=true
org.gradle.java.home=C:/Program Files/Android/Android Studio1/jbr
android.useAndroidX=true
android.enableJetifier=false

# Fix for Windows AAPT2 daemon timeout & resource crunching crashes
android.enableAapt2Daemon=false
android.enableAapt2Worker=false

# Flutter Migrator flags
android.builtInKotlin=false
android.newDsl=false