-- ============================================================================
-- MIGRATION: 001_enterprise_schema.sql
-- DESCRIPTION: Core tables, constraints, indexes, and Row Level Security (RLS)
-- APP: MSM One (Metaroll Steel Mart Operating System)
-- ============================================================================

-- 1. Materials Category Master Table
CREATE TABLE IF NOT EXISTS public.materials (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_name text UNIQUE NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- 2. Item Sizes Master Table
CREATE TABLE IF NOT EXISTS public.item_sizes (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    material_id bigint REFERENCES public.materials(id) ON DELETE CASCADE,
    size_label text NOT NULL,
    unit_weight_kg numeric(12, 4) DEFAULT 0.0000,
    size_difference numeric(12, 2) DEFAULT 0.00,
    current_stock_in numeric(12, 4) DEFAULT 0.0000,
    created_at timestamptz DEFAULT now(),
    CONSTRAINT unique_material_size UNIQUE (material_id, size_label)
);

-- 3. Vendors Master Table
CREATE TABLE IF NOT EXISTS public.vendors (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vendor_name text UNIQUE NOT NULL,
    phone text,
    address text,
    created_at timestamptz DEFAULT now()
);

-- 4. Transactions Ledger Table (Immutable Inventory Log)
CREATE TABLE IF NOT EXISTS public.transactions (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    txn_id text UNIQUE NOT NULL,
    txn_type text NOT NULL CHECK (txn_type IN ('IN', 'OUT', 'TRANSFER', 'ADJUSTMENT', 'OPENING', 'RETURN', 'RESERVE', 'PURCHASE')),
    material_id bigint REFERENCES public.materials(id),
    size_id bigint REFERENCES public.item_sizes(id),
    qty_mt numeric(12, 4) NOT NULL DEFAULT 0.0000,
    location text NOT NULL DEFAULT 'YARD' CHECK (location IN ('YARD', 'FACTORY')),
    to_location text,
    rate numeric(12, 2) DEFAULT 0.00,
    vendor_id bigint REFERENCES public.vendors(id),
    user_name text,
    is_reversed boolean DEFAULT false,
    remark text,
    created_at timestamptz DEFAULT now()
);

-- 5. Global Charges Configuration Table
CREATE TABLE IF NOT EXISTS public.global_charges (
    id text PRIMARY KEY DEFAULT 'singleton',
    gst_rate numeric(5, 2) DEFAULT 18.00,
    lc_rate numeric(10, 2) DEFAULT 255.00,
    nc_discount numeric(10, 2) DEFAULT 3000.00,
    updated_at timestamptz DEFAULT now()
);

-- 6. Performance Indexes
CREATE INDEX IF NOT EXISTS idx_item_sizes_material ON public.item_sizes(material_id);
CREATE INDEX IF NOT EXISTS idx_transactions_material_size ON public.transactions(material_id, size_id);
CREATE INDEX IF NOT EXISTS idx_transactions_created_at ON public.transactions(created_at);
CREATE INDEX IF NOT EXISTS idx_transactions_location ON public.transactions(location);

-- 7. Row Level Security Policies (Read Access for App & Auth Users)
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access on materials" ON public.materials;
CREATE POLICY "Allow public read access on materials" ON public.materials FOR SELECT TO anon, authenticated, postgres USING (true);

ALTER TABLE public.item_sizes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access on item_sizes" ON public.item_sizes;
CREATE POLICY "Allow public read access on item_sizes" ON public.item_sizes FOR SELECT TO anon, authenticated, postgres USING (true);

ALTER TABLE public.vendors ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access on vendors" ON public.vendors;
CREATE POLICY "Allow public read access on vendors" ON public.vendors FOR SELECT TO anon, authenticated, postgres USING (true);

ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access on transactions" ON public.transactions;
CREATE POLICY "Allow public read access on transactions" ON public.transactions FOR SELECT TO anon, authenticated, postgres USING (true);

ALTER TABLE public.global_charges ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access on global_charges" ON public.global_charges;
CREATE POLICY "Allow public read access on global_charges" ON public.global_charges FOR SELECT TO anon, authenticated, postgres USING (true);

-- 8. Grant Table Permissions
GRANT SELECT, INSERT, UPDATE ON public.materials TO anon, authenticated, postgres;
GRANT SELECT, INSERT, UPDATE ON public.item_sizes TO anon, authenticated, postgres;
GRANT SELECT, INSERT, UPDATE ON public.vendors TO anon, authenticated, postgres;
GRANT SELECT, INSERT, UPDATE ON public.transactions TO anon, authenticated, postgres;
GRANT SELECT, INSERT, UPDATE ON public.global_charges TO anon, authenticated, postgres;
